function tables()
println("Table 1")
HistPrint()
println("Table 2")
HistPrint(;nonlinear=false)
println("Table 3")
HistPrint(;nonlinear=false, lasso=[true])
end

function figures()
figure(1)
PlotNew()
title("Figure 1 (a)")
figure(2)
PlotNew(; longplot=true)
title("Figure 1 (b)")
figure(3)
PlotNew(;nonlinear=false)
title("Figure 2 (a)")
figure(4)
PlotNew(; nonlinear=false, longplot=true)
title("Figure 2 (b)")
figure(5)
PlotNew(;nonlinear=false, lasso=[true])
title("Figure 3 (a)")
figure(6)
PlotNew(;nonlinear=false, lasso=[true], longplot=true)
title("Figure 3 (b)")
end

